name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for DB..."
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: test
          DB_PASS: test
          DB_NAME: testdb
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nodejs-api:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/nodejs-api:latest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
      - name: Deploy to Render using API
        run: |
          echo "Triggering Render deploy..."
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "dockerImage": "${{ secrets.DOCKER_USERNAME }}/nodejs-api:${{ github.sha }}",
              "dockerImageVersion": "${{ github.sha }}"
            }')

          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ Deploy failed with status code: $RESPONSE"
            echo "Response:"
            cat response.txt
            exit 1
          else
            echo "✅ Render deployment triggered successfully!"
          fi
